### ISSUE TITLE
[bug]: sending payments overwrites memo field in QR code

### ISSUE THREAD

**Issue by illperipherals** [helium/wallet-issues-tracker#11]
### bug

When sending a payment to Paul (disk91.com), I used the QR code he generates on his site. Payment went through cleanly, but the wallet prompted me for a transaction memo without letting me know that I was overwriting one that had been encoded in the QR. His server checks that memo on his end to validate the account, so it failed.

### Transaction Hash

E9icSJ4UVZuZCIDqUSZ-ZXs3GpOPDF8QYgz-Y4cx5sQ

### Phone Type

Blackview Android (shouldn't matter)

### Network Type

Mainnet

**Comment by tyler-whitman** [comment]
@illperipherals do you have a screenshot of the QR you can provide?
