### ISSUE TITLE
[bug]: Pairing Failed with Ledger Nano X

### ISSUE THREAD

**Issue by lightaprs** [helium/wallet-issues-tracker#15]
### bug

I was trying pair my Ledger Nano X to Wallet but I got "Pairing Failed" error. See secrenshot for details.

* Bluetooth is enabled on my iPhone
* My Ledger Nano X device is opened and unlocked.
* Helium app is installed on Nano X and waiting for command mode.

Yet i got "TypeError: undefined is not a function" error.
![pairing-failed](https://user-images.githubusercontent.com/48382675/165383028-08f94b19-bab4-4fe5-b09b-415a6288b77e.png)

### Phone Type

iPhone 11 Pro 15.4.1

### Network Type

Mainnet

**Comment by radicale** [comment]
Confirmed also with Samsung S10

**Comment by matthewcarlreetz** [comment]
@lightaprs @radicale Could you let me know what version of the Helium app you have installed on your Ledger?

**Comment by lightaprs** [comment]
@matthewcarlreetz Version 1.0 build 78, but I had the same issue with build 77 either.

**Comment by Siegfried-B** [comment]
About the same here, error message a little bit shorter, full message reads: "TypeError: undefined is not a function".
Helium Wallet App Version 1.0, Android 12 on Pixel 4a,
Helium app on Ledger Version 2.3.3

**Comment by radicale** [comment]
> what version of the Helium app you have installed on your Ledger?

Latest available from Ledger Live: 2.2.3

**Comment by KnightAR** [comment]
Same issue, latest version of Ledger 2.41.3, current Google Play 1.0 of app (May 13th), Ledger Nano X on Samsung Galaxy S22 Ultra.

**Comment by cokes518** [comment]
This is fixed now. Please download the new production version of Wallet 1.0. Thanks!
