### ISSUE TITLE
[feature]: Display Last 24 hr amount as HNT not Percentage

### ISSUE THREAD

**Issue by PaulVMo** [helium/wallet-issues-tracker#19]
### feature

As a user, I would like to see the total amount of HNT added to my wallet in the last 24 hours. Currently, the wallet shows a percentage difference (e.g., +25% last 24h). I find this unclear. For example, does that mean the total wallet amount increased 25% in the last 24h or today's increase is +25% higher than yesterdays increase. Even knowing that it is in fact the latter, this numbers not all that informative because it is a relative statistic with no basis for which it is compared to. 

I suggest displaying the last 24h change in HNT amount, or updating it so you can touch on that percentage and have it toggle between the HNT amount and the percentage amount.

**Comment by cokes518** [comment]
great idea paul.
