### ISSUE TITLE
[bug]: Pairing with Ledger Nano X: Helium wallet app uses name of my paired bluetooth headset

### ISSUE THREAD

**Issue by Siegfried-B** [helium/wallet-issues-tracker#4]
### bug

Tried pairing with Ledger Nano X. Interaction seems to work. Number needed to pair the devices shows up correctly on both my phone and on Ledger wallet.
But Helium wallet app assigns name of my paired bluetooth headset - not the name of my Ledger device.

### Phone Type

Pixel 4a, Android 12, newest update installed.

### Network Type

Mainnet

**Comment by cokes518** [comment]
Is this still happening?

**Comment by Siegfried-B** [comment]
No. (Apparently) successfully paired today, this didn't happen again.

**Comment by cokes518** [comment]
good to hear. closing.
