### ISSUE TITLE
[bug]: Pairing with Ledger Nano X using experimental Helium app on Ledger: wallet address not fully shown on Helium wallet app

### ISSUE THREAD

**Issue by Siegfried-B** [helium/wallet-issues-tracker#5]
### bug

Tried pairing with Ledger Nano X. 
During process, Helium wallet app presented option to pair using the already installed (experimental feature) Helium app on Nano X.
I had already created a Helium address on Nano X using CLI feature some time ago.
I was supposed to compare wallet address shown on Helium wallet app and Nano X for being identical.
Address shown in Helium wallet app was shorter than the one on Nano X. What was shown was identical (some very long first part of the address), but the end of the address shown on Nano X was missing.
 Had no idea how to get the Helium wallet app to show me the rest.

### Phone Type

Pixel 4a, Android 12, newest update installed.

### Network Type

Mainnet

**Comment by cokes518** [comment]
We made a fix to ledger recently. Please retest with 1.0, thanks!

**Comment by Siegfried-B** [comment]
Thanks! Tested today. Adress was fully visible - although I had to scroll to do so. Scrolling is fine, but the way the UI is designed, it is far from obvious that scrolling is possible in this part of the screen. Some indication (Ledger e.g. shows a '>' wherever scrolling is possible) when scrolling is possible might be helpful to some users.

**Comment by cokes518** [comment]
closing, looks fixed. thanks!
